package com.lipalater.androidapp.util

const val EMAIL = "email"
const val PASSWORD = "password"
const val PASSWORD_CONFIRMATION = "password_confirmation"
const val FIRST_NAME = "first_name"
const val LAST_NAME = "last_name"
const val ID_NUMBER = "id_number"
const val PHONE_NUMBER = "phone_number"
const val MARITAL_STATUS = "marital_status"
const val GENDER = "gender"
const val IS_EMPLOYED = "employed"
const val EMPLOYER = "employer"
const val NET_MONTHLY_INCOME = "net_monthly_income"
const val NET_MONTHLY_EXPENSES = "net_monthly_expenses"
const val JOB_FUNCTION = "job_function"
const val JOB_LEVEL = "job_level"
const val EMPLOYER_SECTOR = "employer_sector"
const val JOB_GROUP = "job_group"
const val PAYMENT_TYPE = "payment_type"
const val DATE_OF_BIRTH = "date_of_birth"
const val BUSINESS_TYPE = "business_type"
const val BUSINESS_NAME = "business_name"
const val BUSINESS_LOCATION = "business_location"
const val BUSINESS_PAYMENT_TYPE = "business_payment_type"
const val GROSS_MONTHLY_REVENUE = "gross_monthly_revenue"
const val AVERAGE_MONTHLY_EXPENSES = "average_monthly_expenses"
const val AVERAGE_MONTHLY_PERSONAL_EXPENSE = "average_monthly_personal_expense"

const val CONTENT = "content"
